name: Update WakaTime Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Update WakaTime Stats
        uses: athul/waka-readme@v0.2.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # یا secrets.GITHUB_TOKEN اگر توکن شخصی ندارید
          SHOW_TITLE: true
          SECTION_NAME: WakaTime Stats
          TARGET_PATH: README.md
          COMMIT_MESSAGE: 'Update WakaTime stats'
