name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # هر روز در ساعت 00:00 اجرا می‌شود
  workflow_dispatch: # امکان اجرای دستی

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          SECTION_NAME: WakaTime Stats
